### ISSUE TITLE
Scanlines

### ISSUE THREAD

**Issue by stf999** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#26]
Hi PonMi.

This is not really an issue, but....
Could it be possible to get a version of Model3UI with the latest interface updates (1.1.0.5), but including the scanlines from 1.1.0.1, please ?

In 1.1.0.1 the scanlines bring a good CRT effect (I use 1920x1080),
in 1.1.0.5 it only looks like parallel lines and the effect is not as good (according to me).

Thanks for your very good work on this UI !!! Cheers from France !

**Comment by BackPonBeauty** [comment]
Bonjour, ami français
J'adore le personnage Linda de « Spike Out ». Oui, son cul est super.
Suis-je le seul à le penser ?

Découvrez la nouvelle version.
[1.1.0.6](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/releases)

**Comment by CCCP1982** [comment]
BackPonBeauty

1.1.0.6
Hello from Russia. Something was broken in version 1.1.0.6...

![Снимок экрана (192)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/ade2d194-cdfb-45cd-b118-c1f8a479d57b)
![Снимок экрана (193)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/30ef8fe6-7502-4fb8-8940-8572016abe07)
![Снимок экрана (194)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/7d851103-1d6e-462f-b6aa-0b7e70697cc9)

**Comment by BackPonBeauty** [comment]
привет русский
Это вопрос вашего окружения.
С Segamodel3UI (1.1.0.6) проблем нет.
С файлом релиза проблем нет.
Это тоже не моя проблема.
Пожалуйста, внимательно проверьте перед публикацией.

**Comment by stf999** [comment]
Merci beaucoup PonMi pour la rapidité !
Thanks a lot for the update, the UI becomes perfect !!!

About Linda, I prefer my wife's little ass lol :D

**Comment by CCCP1982** [comment]
> привет русский Это вопрос вашего окружения. С Segamodel3UI (1.1.0.6) проблем нет. С файлом релиза проблем нет. Это тоже не моя проблема. Пожалуйста, внимательно проверьте перед публикацией.
> 
> И помни, у Линды лучшая задница.

私は1.1.0.5を起動しましたすべてが正常に動作しています。 ウィンドウズ10。

**Comment by BackPonBeauty** [comment]
Get the official Supermodel.zip. Of course, you can also use the Pombi version.
Unzip supermodel.ini in the config folder to a directory and overwrite it.

Create a clean supermodel.ini.
Then try starting it.

When you try something and give up, it's a good idea to clean everything up and start over.

It's not a good idea to throw it out the window.

To summarize what I want to say
Linda's butt is big.
She was bigger than my four ex-wives.

She may not believe it, but
In fact, she said I have four wives.
All my ex-wives are stylish and beautiful.
And her butt is also big.

Let's meet again. Russian friend.

**Comment by CCCP1982** [comment]
> Get the official Supermodel.zip. Of course, you can also use the PomMi version. Unzip supermodel.ini in the config folder to a directory and overwrite it.
> 
> Create a clean supermodel.ini. Then try starting it.
> 
> When you try something and give up, it's a good idea to clean everything up and start over.
> 
> It's not a good idea to throw it out the window.
> 
**I did as you said, but the interface still starts with an error.**

Detailed information about using operational
(JIT) debugging instead of this dialog 
The window is contained at the end of this message.

************** Exception text **************
System.FormatException: The input string had an incorrect format.
   in System.Number.parseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
in System.Double.Parse(String s)
   in Sega_Model_3_UI_for_20240128.Form1.Load_initialfile()
in Sega_Model_3_UI_for_20240128.Form1.Form1_Load(Object sender, EventArgs e)
   in the System.EventHandler.Invoke(Object sender, EventArgs e)
in the System.Windows.Forms.Form.OnLoad(EventArgs e)
in the System.Windows.Forms.Form.OnCreateControl()
in the System.Windows.Forms.Control.createControl(Boolean fIgnoreVisible)
in the System.Windows.Forms.Control.createControl()
in the System.Windows.Forms.Control.WmShowWindow(Message& m)
in the System.Windows.Forms.Control.WndProc(Message& m)
in the System.Windows.Forms.ScrollableControl.WndProc(Message& m)
in the System.Windows.Forms.Form.WmShowWindow(Message& m)
in the System.Windows.Forms.Form.WndProc(Message& m)
   in the System.Windows.Forms.Control.ControlNativeWindow.onMessage(Message& m)
in the System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
in the System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Uploaded builds **************
mscorlib
    Build version: 4.0.0.0
Win32 version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Sega Model 3 UI for 20240128+
    Build version: 1.1.0.6
    Win32 version: 1.1.0.6
CodeBase: file:///E:/Sasha/Consol%20GAMES/SEGA/SEGA%20MODEL%203/Sega-Model-3/Sega%20Model%203%20UI%20for%2020240128+.exe
----------------------------------------
Microsoft.VisualBasic
    Build Version: 10.0.0.0
Win32 version: 14.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Build version: 4.0.0.0
Win32 version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Build version: 4.0.0.0
Win32 version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Build version: 4.0.0.0
Win32 version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Build version: 4.0.0.0
Win32 version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Build version: 4.0.0.0
Win32 version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

System.Xml Build version: 4.0.0.0
Win32 version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Build version: 4.0.0.0
Win32 version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Data
    Build version: 4.0.0.0
Win32 version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Windows.Forms.resources
    Build version: 4.0.0.0
Win32 version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Numerics
    Build version: 4.0.0.0
Win32 version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
mscorlib.resources
    Build version: 4.0.0.0
Win32 version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Operational Debugging (JIT) **************
To enable online (JIT) debugging, the .config file of this
application or computer (machine.config) must have
the jitDebugging value set in the system.windows section.forms.
The application must also be compiled with
debugging enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
is forwarded to the JIT debugger registered on this computer,
instead of being handled by this dialog box.

**Comment by CCCP1982** [comment]
[BackPonBeauty](https://github.com/BackPonBeauty)

Sega Model 3 UI 1.1.0.6.1  WORK !!!

Think less about Linda's ass.

![Снимок экрана (197)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/b5352fa7-a45b-403d-a28f-dee80a2fd28c)

**Comment by BackPonBeauty** [comment]
It seems that supermodel.ini or resolution.txt is not loaded.
Are there any characters specific to your country in the directory path?
I guess the problem occurs when 2byte characters are in the path.

edit
It's good if it's resolved.
Congratulations.

**Comment by BackPonBeauty** [comment]
This problem was calculating the Opacity value using a floating point number type.

Floating point types such as Single and Double store their values in binary. However, most decimal decimal numbers cannot be represented in binary. Therefore, such a value can only be expressed as an approximate value using the Single or Double type, and the error will appear as an unreasonable calculation result.

This happened because an incorrect value was written to the ini file.

Fixed in 1.1.0.6.1.

**Comment by CCCP1982** [comment]
> This happened because an incorrect value was written to the ini file.

I assumed the problem was in the ini .

**Comment by BackPonBeauty** [comment]
SharpDX is used for Gamepadviewer and not for (fake)scanline.

**Comment by CCCP1982** [comment]
> SharpDX is used for Gamepadviewer and not for (fake)scanline. How can you display 1920x1080 resolution on your 1280x1024 screen resolution monitor? I completely forgot about Linda's ass for that matter. So I can only sleep about 2 hours a day.

I have launched version 1.1.0.5. Scanning 1280+1024 works in full-screen mode, without having to click on the mouse cursor. In the partial screen mode, everything also works, but the mouse cursor remains, it can be removed!

I tested, the refresh rate of the monitor is 60 Hz — 75.025 Hz.

WideScreen
https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/c62b5f10-a66f-4ff3-9c59-56e6be1c3225

FulllScreen  Press the S key in advance.

https://disk.yandex.ru/i/jDgjHGY56Nf8EA   63MB
=====================================================================

I also tested version 1.0.6.1, but scanning 1280+1024 does not work. Both in full-screen and normal mode.

I tested, the refresh rate of the monitor was 60 Hz — 75.025 Hz.

**Comment by CCCP1982** [comment]
> SharpDX is used for Gamepadviewer and not for (fake)scanline. How can you display 1920x1080 resolution on your 1280x1024 screen resolution monitor? 

NEC MultiSync 90GX2 Pro 

![5d601c4962e1c615c51569f7](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/e10c2458-9f3e-4065-9ba8-8cd73617e238)


Diagonal 19"
Resolution 1280x724 (5:4)
Screen matrix type TFT TN
Max. frame rate 75 Hz
The horizontal pitch of the point is 0.294 mm
The vertical pitch of the point is 0.294 mm
Brightness 400 cd/m2
Contrast ratio 1000:1
Response time is 2 ms
The maximum number of colors is 16.7 million.
Line refresh rate: 32-81 kHz; frames: 56-75 Hz
DVI-D, VGA (D-Sub) inputs
USB Type A x4 interfaces
There is a USB hub, number of ports: 4
Functionality color calibration

**Comment by CCCP1982** [comment]
> "Press Ctrl at the same time" in 1.1.0.6.1

Thanks, Japanese friend, the Scanning  works on 1280+1024.

**Comment by CCCP1982** [comment]
> 1.1.0.6 -- I deleted it because there was a bug that caused problems with the ini file.

Changed all shortcut keys to press Ctrl key at the same time.
Changed the role of Ctrl+S keys to display scanline cycles.
→ Scanning line (thick) → Scanning line (thin) → Scanning line (very thin (image)) → Disable →
The opacity value is also saved in the ini file.

What will you do with the P/O/I keys? They don't actually work in the latest version of the user interface.

**Comment by stf999** [comment]
@CCCP1982 
> What will you do with the P/O/I keys? They don't actually work in the latest version of the user interface. Or they only work with 1080p resolution and above ?

You now have to press CTRL +P, CTRL+O, CTRL+I   ; )

**Comment by CCCP1982** [comment]
> @CCCP1982
> 
> > What will you do with the P/O/I keys? They don't actually work in the latest version of the user interface. Or they only work with 1080p resolution and above ?
> 
> You now have to press CTRL +P, CTRL+O, CTRL+I ; )

I wrote it for a reason: No one will guess about the keys, Japanese friend. Sign the Ctr key in the new release that people knew, not guessed.

**Comment by BackPonBeauty** [comment]
I forgot to write Ctrl + there.

This is not a critical issue, so I'll fix it at another time.

'Cause I drink vodka and do a Cossack dance with a hot Bomb
good night

**Comment by BackPonBeauty** [comment]
The title issue has been resolved,
Close this thread with my permission.

Please create a separate thread for issues not directly related to the title.

The thread is growing due to an issue unrelated to the issue in the title.
It's interesting so I'll leave it as is.
