### ISSUE TITLE
A Problem with the Menus (Video, Sound...)

### ISSUE THREAD

**Issue by Kimet1970** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#31]
Is there this problem only with me?
The menus sizes are wrong and you cant to close or alternate to other menus...

![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/82340648/e95cd188-f6ee-4c39-a71e-66683ebb4edb)

**Comment by CCCP1982** [comment]
> Эта проблема только у меня? Размеры меню неправильные, и вы не можете закрыть другие меню или перейти к ним поочередно...
> 

Windows 7 ?  I have Windows 10, everything is showing fine.

**Comment by CCCP1982** [comment]
> Is there this problem only with me? The menus sizes are wrong and you cant to close or alternate to other menus...
> 

Windows 7 ?  I have Windows 10, everything is showing fine.

**Comment by CCCP1982** [comment]
> > Is there this problem only with me? The menus sizes are wrong and you cant to close or alternate to other menus...
> 
> Windows 7 ? [Release 1.1.0.8](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/releases/tag/SupermodelUIver1108) I have Windows 10, everything is showing fine.

The number is 0.7. And it should be 0.8.

**Comment by BackPonBeauty** [comment]
This issue is not worth considering.
It's been a week and I haven't heard anything from anyone else or given them any compliments.

Anyone can scream that something is wrong.

When reporting, you must provide detailed steps to reproduce the issue.
OS, version, CPU, memory, graphic board, driver version, etc.
You lack something to offer.

I think that's your problem.
I will refrain from giving speculative answers.
Please solve it yourself.
Lack of knowledge.

**Comment by BackPonBeauty** [comment]
Was it built with another forked version?
fake image
I think this is a malicious post.
If you don't come out
Please provide steps to reproduce.

**Comment by BackPonBeauty** [comment]
This was a problem with his environment.
It occurred at a specific resolution and with 150% scaling.
Resolved via Discord
