### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by CCCP1982** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#32]
**The window does not automatically have a border position.**

https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/a9910545-0891-4b56-83b0-cc10e088f427

**Comment by BackPonBeauty** [comment]
This issue is not worth considering.
It's been a week and I haven't heard anything from anyone else or given them any compliments.

Anyone can scream that something is wrong.

When reporting, you must provide detailed steps to reproduce the issue.
OS, version, CPU, memory, graphic board, driver version, etc.
You lack something to offer.

I think that's your problem.
I will refrain from giving speculative answers.
Please solve it yourself.
Lack of knowledge.

**Comment by CCCP1982** [comment]
**I won't write about mistakes anymore! You know perfectly well that I have Windows 10 operating system installed. I wish you good luck!**

**Comment by CCCP1982** [comment]
I won't write about mistakes anymore! You know perfectly well that I have Windows 10 operating system installed. I wish you good luck!

**Comment by CCCP1982** [comment]
[BackPonBeauty](https://github.com/BackPonBeauty)

**I found out what the problem was myself! It turned out that the old version of the emulator did not implement the automatic border distribution function.**

(2022-11-03) built for 64-bit
Supermodel_0.3a-git-4c727ab_Win64
https://disk.yandex.ru/d/yjqv0zDSk8YEuQ

**This issue has been resolved in the latest build of the emulator.**

(2024-04-05) built for 64-bit
Supermodel_0.3a-git-250f84e_Win64
