### ISSUE TITLE
Global IP

### ISSUE THREAD

**Issue by TTurbo23** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#39]
Hi There,

I noticed a global IP option. How do you use this to play a friend over the internet?

Thanks,
Terry.

**Comment by BackPonBeauty** [comment]
Here’s the English version of your text:

---

Hello,

If you want to play a linked game with someone over the internet, here is an example of how to set up a 2-link connection.

### Requirements
- Your global IP address (Parent)
- Your partner's global IP address (Slave)
- **Parent** must open port 1970
- **Slave** must open port 1971

### In-game settings
1. In **Game Assign**, set the Parent as "Master" and the Slave as "Slave."

### supermodel.ini setting
1. **Master** settings:
   - **PortIn**: 1970
   - **PortOut**: 1971
   - **AddressOut**: partner's global IP address.
2. **Slave** settings:
   - **PortIn**: 1971
   - **PortOut**: 1970
   - **AddressOut** to your global IP address.

### Startup Procedure
- Start by launching the **Master**. It's a good idea to coordinate over Discord or another communication app.
- Once the **Slave** starts and synchronization is successful, an advertisement (connection notice) will be displayed.
- If the loop completes within 17ms, full-frame play will be possible.

### Notes
- SpikeoutFE The data transfer involves about 17,000 bytes looping every 17ms. Since the **ping command** sends only a 4-byte packet at a time, it’s not a suitable comparison.
- Therefore, you will need a physically close and compatible connection for full-frame play.

### Reference Info
- Someone from Taiwan (or elsewhere) posted a video on **YouTube** demonstrating linked play for *SpikeOut FE* over the internet.
- While the exact settings are unknown, it appears they are using "Legacy" in the **Video Settings**, which may reduce the amount of data required.

---

This translation maintains the same structure and content as the original while ensuring clarity and correctness in English.

**Comment by TTurbo23** [comment]
Excellent, we were doing that and it didn't connect.

Do you need any port forwarding setup?

**Comment by BackPonBeauty** [comment]
Port forwarding setup is required.
The setup method varies depending on the router you're using.
In most cases, you can access the router's settings by entering the default gateway address in your web browser.

For the configuration mentioned earlier:

    The Master must open TCP port 1970.
    The Slave must open TCP port 1971.

The IP address on the LAN side refers to your local IP address.

**Comment by TTurbo23** [comment]
Excellent, this verifies what we did, but now you have confirmed it. Really appreciate your help and skilled work.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TTurbo23** [comment]
Have you seen Blueminders supermodel dojo?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BackPonBeauty** [comment]
I don't know the details about supermodel dojo, but it seems to work in a similar way to Kaillera. It seems to synchronize one model 3 board over the internet. The data on the host side is synchronized to the client side. It works differently from link play.
Sorry, I don't know much about it.
It's easier to use Parsec.

**Comment by BackPonBeauty** [comment]
This thread is not a UI issue so I will close it at my discretion in a week or so.

thanks

PonMi(busy)

**Comment by BackPonBeauty** [comment]
I have two internet connections,
so I tested it.
The IPS is different, but both have the thickest backbone in Japan.

I got about 50 FPS on the first try.
![image](https://github.com/user-attachments/assets/4955f462-2155-484d-b0d0-f690c3d90257)
![image](https://github.com/user-attachments/assets/1bc76338-112b-4ff4-9b7b-16754608f36e)

I revised the settings and got full frames.
![image](https://github.com/user-attachments/assets/b4a2ad02-4eee-46ce-8dbc-fce0a6602b3d)

**Comment by TTurbo23** [comment]
While this is still open, can you please advise what the lan setup should be between 2 pcs on a private network?

**Comment by TTurbo23** [comment]
Yes I must have started using M.A.M.E about 17 years ago. Now I have a Mister FPGA.

**Comment by BackPonBeauty** [comment]
**Explains how to set up 2 links on a LAN.**

**Requirements for 2-PC Linked Play:**
- A properly configured LAN
- **(PC1)** The local IP address of the Master
- **(PC2)** The local IP address of the Slave
- Your motivation
- No need for port forwarding.

First, open the command prompt on **PC1** and type `ipconfig` to obtain the local IP address. Avoid using the IPv6 address, as it looks like Martian symbols; instead, take note of the IPv4 address. Do the same on **PC2** and note its IP address. It will usually be something like `192.168.0.n`.

### Master (PC1) INI file configuration:
- **PortIn**: 1970
- **PortOut**: 1971
- **AddressOut**: Slave's IP address

### Slave (PC2) INI file configuration:
- **PortIn**: 1971
- **PortOut**: 1970
- **AddressOut**: Master’s IP address

**In-game settings are the same as before**:  
Set **Master** as "Master" and **Slave** as "Slave". For a 3-link setup, the third link is also a **Slave**. Each set can only have one **Master**; the rest are **Slaves**.

For a **3-link setup**:
- **PC1 settings**:  
- **PortIn**: 1970
- **PortOut**: 1971
- **AddressOut**: PC2's IP address
- **PC2 settings**:  
  - **PortIn**: 1971  
  - **PortOut**: 1972  
  - **AddressOut**: PC3's IP address  
- **PC3 settings**:  
  - **PortIn**: 1972  
  - **PortOut**: 1970  
  - **AddressOut**: PC1’s IP address  

### Startup Procedure
It’s recommended to launch from the **Master**, but you can start from a **Slave** as well. However, it's best to start both almost simultaneously. If the setup fails, make sure to close everything and restart.

### Key Settings
For *Spikeout FE*, the key settings on all PCs (PC1, PC2, and PC3) should be configured as **JOY1**.

### Other setting
It’s better to enable the throttle only on the Master, and leave it unchecked on the Slaves.
Use the same settings except for the throttle.
Use the same version of Supermodel.exe.

Unrelated, but if you're building a link with one PC, uncheck EmulatedDSB on everything except the Master, as it will crash sporadically.
It may have been fixed though.

**Comment by BackPonBeauty** [comment]
[SANWA](https://www.sengoku.co.jp/mod/sgk_cart/detail.php?code=EEHD-68Z6)) Shaft Detachable Joystick Lever 【JLXD-TP-8YT】
This joystick has a detachable shaft, making it easy to carry.
![014481c3fcd75cae1da6c070c8a426ea030c48dc78b246b49ddaf9ef2f67b889](https://github.com/user-attachments/assets/05ab94b9-bd7c-447c-8c8a-e3de810848c4)

[GamerFinger](https://www.sengoku.co.jp/mod/sgk_cart/detail.php?code=EEHD-5J6E))This is a kit that changes the input method of Sanwa Denshi joysticks (JLF series) from a microswitch to an optical sensor.
![684cd274ed5d715b1175db95b98ffc0d712815b1d5d26ce29122b3ff29d917ba](https://github.com/user-attachments/assets/fbd708db-7e30-410e-92bf-5be5a87381b8)
All buttons are Sanwa OBS C-30/24-CR The color scheme is based on the Spike Out FE color scheme.
Use one or two silicone rubber flat washers SIW-1625-10 (inner diameter 16 mm, outer diameter 25 mm, thickness 1 mm) to reduce noise.
![PXL_20240905_174625867](https://github.com/user-attachments/assets/486e9147-c933-4e0b-81aa-8a4b3aabfb8b)
Brook unvesal fighting board XB
![81nLpxfUzNL _AC_SL1500_](https://github.com/user-attachments/assets/c9377d91-2e12-49bd-85be-96933a300884)
case GameSir C2
![51ROARWSywL _AC_SL1000_](https://github.com/user-attachments/assets/a9597d45-3652-4fcf-92e2-aeb8253ad8f3)

**Comment by TTurbo23** [comment]
Pretty sure I pointed out and made reference to you as the owner of github and the supermodel ui. I never claimed I was the source.

Sorry you feel that way as it wasn't my intention.

Also, to say that to me and then spam me with lots of sales adverts without my consent could be construed as harassment.

Im not sure what yiu arw teying to achieve here.



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BackPonBeauty** [comment]
Someone has reviewed the application

August 12, 2024
It seems that after the 8/8 update, ads have started appearing in my inbox. Even though I have a Microsoft 365 contract, I seem to be treated as a "free user". It's very annoying, so I hope they improve it as soon as possible. By the way, ads are not displayed on the PC version. It's a shame because there is nothing wrong with the app.
10 users found this review helpful

PonMi(I’m not an email bomber.)

**Comment by BackPonBeauty** [comment]
This is a place to discuss UI issues.

And this title has nothing to do with UI, it's just a question.

I answered this politely, but he didn't seem to be grateful.

Oh, I said something unnecessary again.

You don't need to reply anymore.

Shhh.

And this will be reused as my diary.

Hahaha.

Just kidding. I'm closing this with my authority.

I'll do it sometime soon.

**Comment by TTurbo23** [comment]
Why did you use an AI generated response?

Best Regards,
Terry.
________________________________
